import { Menu } from "./menu.model";

export const verticalMenuItems = [
  new Menu(3, "Dashboard", "/app/dashboard", null, "dashboard", null, true, 0),
  new Menu(
    1,
    "SUB Audits",
    "/app/subjective-audits",
    null,
    "find_in_page",
    null,
    false,
    0,
  ),
  new Menu(
    2,
    "OBJ Audits",
    "/app/objective-audits",
    null,
    "find_in_page",
    null,
    false,
    0,
  ),
  new Menu(6, "PRTS", "/app/prts-part", null, "request_quote", null, false, 0),
  new Menu(4, "Admin", "/app/admin", null, "supervisor_account", null, true, 0),
  new Menu(
    401,
    "Roles & Users",
    "/app/admin/manage-users",
    null,
    "group_add",
    null,
    false,
    4,
  ),
  new Menu(
    403,
    "Dashboard",
    "/app/admin/lookups",
    null,
    "search",
    null,
    false,
    4,
  ),
  new Menu(
    404,
    "Preferences",
    "/app/admin/settings",
    null,
    "settings_applications",
    null,
    false,
    4,
  ),
  new Menu(
    405,
    "Event Log",
    "/app/admin/event-log",
    null,
    "engineering",
    null,
    false,
    4,
  ),
  new Menu(
    406,
    "Escalation Matrix",
    "/app/admin/escalation",
    null,
    "mail_outline",
    null,
    false,
    4,
  ),
  new Menu(
    2,
    "OBJ Audits",
    "/app/objective-audits",
    null,
    "find_in_page",
    null,
    false,
    0,
    ["/app/setup/subjective/check"],
  ),
];

export const horizontalMenuItems = [
  new Menu(1, "Dashboard", "/app/test-dashboard", null, "dashboard", null, false, 0),
  new Menu(2, "Projects", "/app/testing/projects", null, "business_center", null, false, 0),
  new Menu(3, "Stages", "/app/testing/stages", null, "layers", null, false, 0),
  new Menu(4, "Gates", "/app/testing/gates", null, "door_front", null, false, 0),
  new Menu(5, "Master Data", "/app/testing/testing-masterData", null, "storage", null, false, 0),
  // new Menu(6, "Tasks", "/app/testing/tasks", null, "task", null, false, 0),
  // new Menu(7, "Issues", "/app/testing/issues", null, "bug_report", null, false, 0),
  // new Menu(8, "To Do", "/app/testing/todo", null, "checklist", null, false, 0),
  new Menu(9, "Activity", "/app/test-activity", null, "people", null, false, 0),
  new Menu(10, "Resources", "/app/testing/resources", null, "people", null, false, 0),
];

export const clientMenuItems = [
  new Menu(
    1,
    "Client",
    "/app/client-login",
    null,
    "account_circle",
    null,
    false,
    0,
  ),
];

export const supplierMenuItems = [
  new Menu(
    404,
    "Lookup Options",
    "/app/admin/lookups",
    null,
    "search",
    null,
    false,
    0,
  ),

  new Menu(
    404,
    "Dashboard",
    "/app/admin/lookups",
    null,
    "search",
    null,
    false,
    0,
  ),
];
